# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:  
    branches:
      only:
        - dev-ng
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo npm install -g @angular/cli@7.3.5
      - run: sudo npm install -g ngh
      - run: npm install
      - run: npm rebuild node-sass

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Generate build!
      - run: 
          name : Genereate prod build package
          command : ng build --prod --output-path="prod"
      - run:
          name : Publishing package to gh-pages
          command : |
              echo "AUTHOR" ${GIT_AUTHOR_NAME}
              echo "EMAIL" $EMAIL
              git config --global user.email "zmrfzn@gmail.com"
              git config --global user.name "Zameer"
              git config --global push.default simple
              git add package-lock.json; git commit -m "commit to be lost"      
              git checkout gh-pages-tests
              git add prod/*
              git commit -m "Circle CI PROD Build push"; git push origin gh-pages-tests
